// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAixz0nv95DJvnZFh_uMWptoaEQ4CA13eE',
    appId: '1:417929578745:web:2a1661f7e0c2e78dea7a28',
    messagingSenderId: '417929578745',
    projectId: 'techdesigncenter-84455',
    authDomain: 'techdesigncenter-84455.firebaseapp.com',
    storageBucket: 'techdesigncenter-84455.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCagnZ2dlfT-Iq_OEWSAJ3pj_8aBehoHa8',
    appId: '1:417929578745:android:a06f3602e07e0f57ea7a28',
    messagingSenderId: '417929578745',
    projectId: 'techdesigncenter-84455',
    storageBucket: 'techdesigncenter-84455.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCiuF62BVsGENtXucoNuLog6LIFUzJx3k',
    appId: '1:417929578745:ios:98b25cb9acefef03ea7a28',
    messagingSenderId: '417929578745',
    projectId: 'techdesigncenter-84455',
    storageBucket: 'techdesigncenter-84455.appspot.com',
    iosClientId: '417929578745-coijtok5lng8vau6jrhq1v1g48oegs8s.apps.googleusercontent.com',
    iosBundleId: 'com.example.tdcFrontendMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCiuF62BVsGENtXucoNuLog6LIFUzJx3k',
    appId: '1:417929578745:ios:98b25cb9acefef03ea7a28',
    messagingSenderId: '417929578745',
    projectId: 'techdesigncenter-84455',
    storageBucket: 'techdesigncenter-84455.appspot.com',
    iosClientId: '417929578745-coijtok5lng8vau6jrhq1v1g48oegs8s.apps.googleusercontent.com',
    iosBundleId: 'com.example.tdcFrontendMobile',
  );
}
